FROM php:7.2-cli

LABEL io.kuzzle.vendor="Kuzzle <support@kuzzle.io>"
LABEL description="Runner for php documentation snippets"
LABEL name="kuzzleio/doc-runner:php"

RUN docker-php-source extract

WORKDIR /app