---

snippets:
  mount: /mnt
  path: doc/**/snippets/*.test.yml
  templates: /mnt/.ci/doc/templates

runners:
  default: php

  php:
    service: doc-runner-php
    path: /var/snippets/php
    build:
      cmd: php /composer.phar require kuzzleio/kuzzle-sdk
    lint:
      cmd: php -l {{ snippet.source }}
    run:
      cmd: php {{ snippet.source }}
      before: timeout 600 bash -c 'until curl -f -s -o /dev/null http://kuzzle:7512/_now; do sleep 1; done'