version: '3'

services:
  doc:
    image: kuzzleio/documentation:dev
    ports:
      - 8080:8080
    tty: true
    volumes:
      - cache:/var/app/node_modules/@vuepress/core/node_modules/.cache
      - ./:/var/app/src/sdk/php

volumes:
  cache: